export const FETCH_CURRENCIES_REQUEST = 'FETCH_CURRENCIES_REQUEST';
export const FETCH_CURRENCIES_SUCCESS = 'FETCH_CURRENCIES_SUCCESS';
export const FETCH_CURRENCIES_ERROR = 'FETCH_CURRENCIES_ERROR';

export const FETCH_MARKET_CURRENCIES_REQUEST =
  'FETCH_MARKET_CURRENCIES_REQUEST';
export const FETCH_MARKET_CURRENCIES_SUCCESS =
  'FETCH_MARKET_CURRENCIES_SUCCESS';
export const FETCH_MARKET_CURRENCIES_ERROR = 'FETCH_MARKET_CURRENCIES_ERROR';

export const CHANGE_TARGET_CURRENCY = 'CHANGE_TARGET_CURRENCY';
